// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBilu5B9TTbrQhu0aSrwHzl6kfYr0bT0hk',
    appId: '1:1079107128524:web:a7f65989879ff4fc51c669',
    messagingSenderId: '1079107128524',
    projectId: 'app-iot-77dd8',
    authDomain: 'app-iot-77dd8.firebaseapp.com',
    storageBucket: 'app-iot-77dd8.firebasestorage.app',
    measurementId: 'G-5HRSP8XTFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJHMbRiKtnft4E1D6s8W_Bi3wJB4R_tM',
    appId: '1:1079107128524:android:b3988034e0ec8f7751c669',
    messagingSenderId: '1079107128524',
    projectId: 'app-iot-77dd8',
    storageBucket: 'app-iot-77dd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBWYcNvJMPEpwvE91tYQv5K-TCUR-sXKo',
    appId: '1:1079107128524:ios:06b7d1db4059fbec51c669',
    messagingSenderId: '1079107128524',
    projectId: 'app-iot-77dd8',
    storageBucket: 'app-iot-77dd8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBWYcNvJMPEpwvE91tYQv5K-TCUR-sXKo',
    appId: '1:1079107128524:ios:06b7d1db4059fbec51c669',
    messagingSenderId: '1079107128524',
    projectId: 'app-iot-77dd8',
    storageBucket: 'app-iot-77dd8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBilu5B9TTbrQhu0aSrwHzl6kfYr0bT0hk',
    appId: '1:1079107128524:web:05ccb46b770c75f051c669',
    messagingSenderId: '1079107128524',
    projectId: 'app-iot-77dd8',
    authDomain: 'app-iot-77dd8.firebaseapp.com',
    storageBucket: 'app-iot-77dd8.firebasestorage.app',
    measurementId: 'G-KG0WVNYWY2',
  );
}
